mixed-port: 7890
allow-lan: false
log-level: info
# external-controller: 127.0.0.1:9090
external-controller: 0.0.0.0:9090
external-ui: /ui
secret: ""
ipv6: false
proxies:
  - name: jp
    type: vmess
    server: xx.xxx.com
    port: 1984
    uuid: 4b2e512f-abcd-abcd-abcd-06131fac6112
    alterId: 32
    cipher: auto
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - jp
rules:
  - DOMAIN-KEYWORD,youtube.com,Proxy
  - DOMAIN-KEYWORD,google.com,Proxy
  - MATCH,DIRECT
