FROM paddlepaddle/paddle:2.3.2
LABEL maintainer="imaguowei@gmail.com"
LABEL name="maguowei/paddlenlp"
LABEL version="0.2.0"

RUN pip install paddlenlp && \
    pip install pypinyin && \
    pip install ipython

CMD ["ipython"]
