name: base
on:
  workflow_dispatch:
  push:
    paths:
      - "base/*"
      - ".github/workflows/base.yaml"
jobs:
  App:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: maguowei/base
