name: base
on: 
  push:
    paths:
    - 'base/*'
jobs:
  App:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maguowei/base
          path: base
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
