name: go
on: 
  push:
    paths:
    - 'go/**'
jobs:
  App:
    name: Build go-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maguowei/go-app
          tags: onbuild
          path: go/app
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
  Builder:
    name: Build go-builder
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maguowei/go-builder
          tags: onbuild
          path: go/builder
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true