on: push
name: Build
jobs:
  dockerLogin:
    name: Docker login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker build surge-snell
      uses: actions/docker/cli@master
      with:
        args: build -t maguowei/surge-snell surge-snell
    - name: Docker build shadowsocks
      uses: actions/docker/cli@master
      with:
        args: build -t maguowei/shadowsocks shadowsocks
    - name: Docker build python-app
      uses: actions/docker/cli@master
      with:
        args: build -t maguowei/python-app:onbuild python-app
    - name: Docker build base
      uses: actions/docker/cli@master
      with:
        args: build -t maguowei/base base
    - name: Docker build python
      uses: actions/docker/cli@master
      with:
        args: build -t maguowei/python python
    - name: Docker push surge-snell
      uses: actions/docker/cli@master
      with:
        args: push maguowei/surge-snell
    - name: Docker push shadowsocks
      uses: actions/docker/cli@master
      with:
        args: push maguowei/shadowsocks
    - name: Docker push python-app
      uses: actions/docker/cli@master
      with:
        args: push maguowei/python-app:onbuild
    - name: Docker push base
      uses: actions/docker/cli@master
      with:
        args: push maguowei/base
    - name: Docker push python
      uses: actions/docker/cli@master
      with:
        args: push maguowei/python
