name: surge-snell
on:
  workflow_dispatch:
  push:
    paths:
    - 'surge-snell/*'
jobs:
  App:
    name: Build surge-snell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: surge-snell
          push: true
          tags: maguowei/surge-snell
